version: '3.8'

services:
  dgsg_dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile.x86_64
    privileged: true
    image: dgsg-dev:latest
    command: bash # Keep the container running for interactive use
    tty: true
    stdin_open: true
    container_name: dgsg_dev_container
    network_mode: "host"
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - ../../Dynamic-GSG:/workspace/Dynamic-GSG # Mount the aiortc_bridge directory
      - /tmp/.X11-unix:/tmp/.X11-unix:rw  # Mount the X11 socket

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
